# A notebook to parse URLs from messages in the database

In [1]:
from sqlalchemy import select, create_engine, Table, Column, Integer, ForeignKey, func, cast

from telegram_data_models import Message, Chat, Entity, EntityURL, ChatLanguage

from datetime import datetime

from itertools import batched

import dask.dataframe as dd
from dask.distributed import Client, LocalCluster

from dask_jobqueue.slurm import SLURMCluster

import os
import shutil
import numpy as np
import pandas as pd
from pathlib import Path
from functools import partial
from tqdm.notebook import tqdm

from telegram_quality_control.urls import batch_rate_urls
from telegram_quality_control.db import get_conn_string

from dotenv import load_dotenv

load_dotenv(".env")

ValueError: ('The database driver was not provided as an argument and ', 'the DB_DRIVER environment variable is not set.')

In [4]:
lang = 'en'
lang_score = 0.8

test_run = False

num_workers = 64  # number of parallel workers to use
if test_run:
    chunk_size = 100  # number of entities to process in one chunk
else:
    chunk_size = 10_000

scratch_folder = Path(os.environ.get("SCRATCH_FOLDER")) / "urls" / "updated"
print(f"Scratch folder: {scratch_folder}")
scratch_folder.mkdir(parents=True, exist_ok=True)

data_folder = Path(os.environ.get("OUTPUT_FOLDER"))
print(f"Data folder: {data_folder}")
data_folder.mkdir(parents=True, exist_ok=True)

Scratch folder: /data/nst/agolovin/envs/quality_control/urls/updated
Data folder: data

In [5]:
db_url = get_conn_string()

chat_table = Chat.__table__
message_table = Message.__table__
language_table = ChatLanguage.__table__
entity_url_table = EntityURL.__table__

In [4]:
# pre-load entity ids
url_path = scratch_folder / "urls.parquet"

if not url_path.exists():
    print("Downloading the URLs")
    sql = (
        select(
            entity_url_table.c.entity_id,
            entity_url_table.c.message_id,
            entity_url_table.c.url,
        )
        .join(message_table, message_table.c.id == entity_url_table.c.message_id)
        .join(language_table, language_table.c.chat_id == message_table.c.chat_id)
        .where(language_table.c.lang == lang)
        .where(language_table.c.score > 0.8)
    )

    urls = pd.read_sql_query(sql, db_url)

    urls.to_parquet(url_path)

In [5]:
urls = dd.read_parquet(url_path)
len(urls)

61972016

In [ ]:
if test_run:
    cluster = LocalCluster(n_workers=num_workers, threads_per_worker=1, memory_limit="4GB")
    client = Client(cluster)
else:
    cluster = SLURMCluster(
        cores=1,
        processes=2,
        memory="16GB",
        queue="nariman",
        interface="ens4f0np0",
        walltime="02:00:00",
        log_directory="./logs",
    )
    cluster.scale(num_workers)
    client = cluster.get_client()

print(f"Dashboard URL: {client.dashboard_link}")

Dashboard URL: http://172.19.100.44:8787/status

In [ ]:
url_ddf = dd.read_parquet(url_path)

display(url_ddf)

num_partitions = url_ddf.npartitions

larger_than_memory = num_partitions
print(
    f"Warning: the DataFrame is larger than memory and will be processed in {num_partitions} partitions."
)

for col in ["message_id", "url"]:
    if col not in url_ddf.columns:
        raise ValueError(f"The DataFrame must contain a '{col}' column.")

url_ddf = url_ddf.repartition(npartitions=num_workers * url_ddf.npartitions * 10)

url_ddf

Dask DataFrame Structure:
               entity_id message_id     url
npartitions=30
                   int64      int64  string
                     ...        ...     ...
...                  ...        ...     ...
                     ...        ...     ...
                     ...        ...     ...
Dask Name: read_parquet, 1 expression
Expr=ReadParquetFSSpec(6356900)

Warning: the DataFrame is larger than memory and will be processed in 30 partitions.

Dask DataFrame Structure:
                  entity_id message_id     url
npartitions=19200
                      int64      int64  string
                        ...        ...     ...
...                     ...        ...     ...
                        ...        ...     ...
                        ...        ...     ...
Dask Name: repartition, 2 expressions
Expr=Repartition(frame=ReadParquetFSSpec(6356900), new_partitions=19200)

In [ ]:
matched_url_df = batch_rate_urls(url_ddf, url_col="url", version="updated")

# repartition to fewer partitions
matched_url_df = matched_url_df.repartition(npartitions=num_partitions)

if larger_than_memory:
    # sink to many files, then concat them.
    matched_url_df.to_parquet(scratch_folder / "matched_urls")
else:
    matched_url_df.to_parquet(scratch_folder / "matched_urls.parquet")

Using Dask for parallel processing of URLs.

In [3]:
matched_url_df = dd.read_parquet(scratch_folder / "matched_urls")

# filter only the columns that are relevant for the analysis: not blacklisted, reliability ranking exists for at least one version
ranking_exists = matched_url_df["reliability"].notnull()

mask = (~matched_url_df["is_blacklisted"]) & ranking_exists
ranked_url_df = matched_url_df[mask]
print(f"Number of relevant URLs: {len(ranked_url_df)}")

ranked_url_df = ranked_url_df.reset_index(drop=True)
ranked_url_df.to_parquet(scratch_folder / "ranked_urls")

Number of relevant URLs: 16716818

In [7]:
# concat all ranked urls to one df

dfs = []
for file in (scratch_folder / "ranked_urls").glob("*.parquet"):
    df_part = pd.read_parquet(file)
    dfs.append(df_part)

ranked_url_df = pd.concat(dfs, ignore_index=True)
ranked_url_df.reset_index(inplace=True, drop=True)
ranked_url_df.to_parquet(data_folder / "ranked_urls_telegram.parquet")

# remove the old folder
# shutil.rmtree(scratch_folder / "ranked_urls")

In [8]:
ranked_url_df = dd.read_parquet(data_folder / "ranked_urls_telegram.parquet")
len(ranked_url_df)

17419582